### ISSUE TITLE
PostgreSQL update command exceptions

### ISSUE THREAD

**Issue by soukudom** [IOT-DSA/dslink-java-jdbc#17]
Using jdbc dslink with PostgreSQL db I'm receiving below log messages. However, the SQL command is processed correctly.

> org.postgresql.util.PSQLException: No results were returned by the query.
> [2019-07-25 16:17:59.426766]    at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
> [2019-07-25 16:17:59.426773]    at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:310)
> [2019-07-25 16:17:59.426782]    at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:310)
> [2019-07-25 16:17:59.426789]    at org.dsa.iot.jdbc.handlers.QueryHandler.doQuery(QueryHandler.java:67)
> [2019-07-25 16:17:59.426795]    at org.dsa.iot.jdbc.handlers.QueryHandler.handle(QueryHandler.java:47)
> [2019-07-25 16:17:59.426801]    at org.dsa.iot.jdbc.handlers.QueryHandler.handle(QueryHandler.java:23)
> [2019-07-25 16:17:59.426807]    at org.dsa.iot.dslink.node.actions.Action.invoke(Action.java:159)
> [2019-07-25 16:17:59.426816]    at org.dsa.iot.dslink.methods.responses.InvokeResponse.getJsonResponse(InvokeResponse.java:164)
> [2019-07-25 16:17:59.426822]    at org.dsa.iot.dslink.link.Responder.parse(Responder.java:126)
> [2019-07-25 16:17:59.426864]    at org.dsa.iot.dslink.DSLink$2.handle(DSLink.java:171)
> [2019-07-25 16:17:59.426873]    at org.dsa.iot.dslink.DSLink$2.handle(DSLink.java:163)
> [2019-07-25 16:17:59.426880]    at org.dsa.iot.dslink.connection.DataHandler$1.run(DataHandler.java:89)
> [2019-07-25 16:17:59.426939]    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [2019-07-25 16:17:59.427026]    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [2019-07-25 16:17:59.427077]    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> [2019-07-25 16:17:59.427089]    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> [2019-07-25 16:17:59.427142]    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [2019-07-25 16:17:59.427219]    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [2019-07-25 16:17:59.427259]    at java.lang.Thread.run(Thread.java:748)

This issue is unpleasant because log space is heavily used. Possible solution is here: https://stackoverflow.com/questions/21276059/no-results-returned-by-the-query-error-in-postgresql

**Comment by dglogik** [comment]
@soukudom thanks for the bug report. We will look into it.

**Comment by d-shapiro** [comment]
@soukudom For queries that don't return any data, use the "Update" action instead of the "Query" action. This will prevent these error messages.

**Comment by soukudom** [comment]
Thanks a lot!
